repo_url: https://github.com/Interacao-Humano-Computador/2024.1-DETRANDF
repo_name: 2024.1-DETRANDF

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

site_name: Portal DETRAN-DF


nav:
  - Home: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
      - Apresentação 3: apresentacao/apresentacao3.md
  - Atas:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Heatmap: planejamento/heatmap.md
    - Sites avaliados: planejamento/sites-avaliados.md
    - Processo de design: planejamento/processo-de-design.md
  - Análise de Requisitos:
    - Análise de Tarefas: 
      - Análise Hierárquica de Tarefas: analise-requisitos/aht.md
      - GOMS: analise-requisitos/goms.md
    - Características da Plataforma: analise-requisitos/caracteristicas-plataforma.md



theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro


  language: pt-BR
  favicon: planejamento/logos/favicon/favicon.png
  logo: planejamento/logos/favicon/apple-touch-icon.png

extra:
  version:
    provider: mike
  
extra_css: [stylesheets/extra.css]