repo_url: https://github.com/Interacao-Humano-Computador/2024.1-DETRANDF
repo_name: 2024.1-DETRANDF

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

site_name: Portal DETRAN-DF


nav:
  - Home: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
      - Apresentação 3: apresentacao/apresentacao3.md
      - Apresentação 4: apresentacao/apresentacao4.md
      - Apresentação 6.1: apresentacao/apresentacao6.1.md
  - Atas:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
      - Ata 3: atas/ata3.md
      - Ata 4: atas/ata4.md
      - Ata 5: atas/ata5.md
      - Ata 6: atas/ata6.md
      - Ata 7: atas/ata7.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Heatmap: planejamento/heatmap.md
    - Metodologia: planejamento/metodologia.md
    - Sites avaliados: planejamento/sites-avaliados.md
    - Site escolhido: planejamento/site-escolhido.md
    - Processo de design: planejamento/processo-de-design.md
  - Análise de Requisitos:
    - Aspectos Éticos: analise-requisitos/aspectos-eticos.md
    - Perfil do Usuário: analise-requisitos/usuario.md
    - Personas: analise-requisitos/personas.md
    - Cenários: analise-rerquisitos/cenarios.md
    - Análise de Tarefas: 
      - Análise Hierárquica de Tarefas: analise-requisitos/aht.md
      - GOMS: analise-requisitos/goms.md
    - Metas de Usabilidade: analise-requisitos/metas-usabilidade.md
    - Principios Gerais: analise-requisitos/pgerais.md
    - Guia de Estilo: analise-requisitos/guia-estilo.md
    - Características Gerais: analise-requisitos/caracteristicas-plataforma.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
        - Análise de Tarefas:
            - Planejamento da Avaliação da Análise de Tarefas: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/planejamento-avaliacao-at.md
            - Planejamento do Relato dos Resultados da Avaliação: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/planejamento-relato-resultado-at.md
            - Relato dos Resultados da Avaliação: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/relato-resultado-at.md
        - Storyboard:
            - Planejamento da Avaliação do Storyboard: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/planejamento-avaliacao-sb.md
            - Planejamento do Relato dos Resultados: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/planejamento-relato-resultado-sb.md
            - Relato dos Resultados da Avaliação: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/relato-resultado-storyboard.md
            - Storyboards: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/storyboard.md
    - Nível 2:
      - Protótipo de Papel:
          - Planejamento da Avaliação do Protótipo de Papel: design-avaliacao-desenvolvimento/nivel-2/planejamento-avaliacao-pp.md
          - Planejamento do Relato dos Resultados: design-avaliacao-desenvolvimento/nivel-2/planejamento-relato-resultados-pp.md
          - Relato dos Resultados:
            - Solicitar PID: design-avaliacao-desenvolvimento/nivel-2/relato-resultados-pp/solicitar-pid.md
            - Emitir CRLV-e: design-avaliacao-desenvolvimento/nivel-2/relato-resultados-pp/emitir-crlv.md
            - Emissão Nada Consta da CNH: design-avaliacao-desenvolvimento/nivel-2/relato-resultados-pp/emissao-nada-consta.md
    - Nível 3:
      - Protótipo de Alta Fidelidade: 
          - Planejamento da Avaliação do Protótipo de Alta Fidelidade: design-avaliacao-desenvolvimento/nivel-3/planejamento-avaliacao-paf.md       
          - Planejamento do Relato dos Resultados - Protótipo de Alta Fidelidade: design-avaliacao-desenvolvimento/nivel-3/planejamento-relato-prototipo-alta.md       
  - Verificação:
    - Etapa 2:
      - Planejamento da Verificação da Etapa 2: verificacao/grupo-07/etapa-2/planejamento.md
      - Perfil do usuário: verificacao/grupo-07/etapa-2/perfil-usuario.md
      - Personas: verificacao/grupo-07/etapa-2/personas.md
      - Cenários: verificacao/grupo-07/etapa-2/cenarios.md
      - Aspectos éticos: verificacao/grupo-07/etapa-2/aspectos-eticos.md
      - Análise de Tarefas: verificacao/grupo-07/etapa-2/analise-tarefas.md
    - Etapa 4: 
      - Planejamento da Verificação da Etapa 4: verificacao/grupo-07/etapa-4/planejamento-verificacao-etapa-4.md
      - Planejamento da Avaliação da Análise de Tarefas: verificacao/grupo-07/etapa-4/verificacao-planejamento-avaliacao-at.md
      - Planejamento do Relato dos Resultados da Avaliação Análise de Tarefas: verificacao/grupo-07/etapa-4/verificacao-planejamento-relato-resultado-at.md
      - Planejamento da Avaliação do Storyboard: verificacao/grupo-07/etapa-4/verificacao-planejamento-avaliacao-sb.md
      - Planejamento do Relato dos Resultados da Avaliação dos Storyboards: verificacao/grupo-07/etapa-4/verificacao-planejamento-relato-resultado-sb.md
      - Storyboards: verificacao/grupo-07/etapa-4/verificacao-sb.md
    - Etapa 5: 
      - Planejamento da Verificação da Etapa 5: verificacao/grupo-07/etapa-5/planejamento-verificacao-etapa-5.md
      - Relato dos Resultados da Análise de Tarefas: verificacao/grupo-07/etapa-5/relato-resultados-at.md
      - Relato dos Resultados do Storyboard: verificacao/grupo-07/etapa-5/relato-resultados-storyboard.md
      - Planejamento da Avaliação do Protótipo de Papel: verificacao/grupo-07/etapa-5/planejamento-avaliacao-prototipo.md
      - Planejamento do Relato dos Resultados da Avaliação do Protótipo de Papel: verificacao/grupo-07/etapa-5/planejamento-relato-prototipo.md



theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro


  language: pt-BR
  favicon: planejamento/logos/favicon/favicon.png
  logo: planejamento/logos/favicon/apple-touch-icon.png

extra:
  version:
    provider: mike
  
extra_css: [stylesheets/extra.css]